#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_LDFLAGS = -lm

MODULE_CLASSES = MsgLogger

SRC_FILES= MsgLogger.cpp

include $(MODULE_MAKEFILE)

