#ifndef LCACC_COMMAND_LISTING_H
#define LCACC_COMMAND_LISTING_H

#define GAM_CMD_REQUESTCOUNT 10
#define GAM_CMD_RESPONDCOUNT 11
#define GAM_CMD_REQUEST 1
#define GAM_CMD_RELEASE 2
#define GAM_CMD_RESERVE 3
#define GAM_CMD_ACCCONFIRM 4
#define GAM_CMD_REQRESPONSE 5
#define GAM_CMD_ACCNOTIFY 6
#define DMA_MEMORY_REQUEST 40
#define DMA_MEMORY_RESPONSE 41
#define LCACC_CMD_BEGIN_TASK 42
#define LCACC_CMD_CANCEL_TASK 43
#define LCACC_CMD_TLB_SERVICE 44
#define LCACC_CMD_TLB_MISS 45
#define LCACC_CMD_TASK_COMPLETED 46
#define LCACC_CMD_BEGIN_TASK_SIGNATURE 47
#define LCACC_CMD_BEGIN_EMBEDDED_TASK_SIGNATURE 48
#define TD_CMD_BEGIN_PROGRAM 50
#define TD_CMD_CLEAR_FILTER 52
#define TD_CMD_ADD_FILTER 53
#define BIN_CMD_ARBITRATE_REQUEST 101
#define BIN_CMD_ARBITRATE_RESPONSE 102
#define LCA_RAISE_SIGNAL 201

#endif
