#include "PatternSelector.hh"
#include "GreedySelector.hh"
#include "DumbSelector.hh"
#include "SoftSelector.hh"
#include "ExclusiveDumbSelector.hh"
#include "SmoothMemorySelector.hh"
#include "MinChainSelector.hh"
