# -*- mode:python -*-

import os
import sys

from os.path import basename, isdir, join as joinpath

import SCons

Import('*')

Source('MemoryDeviceInterface.cc')
Source('MeteredMemory.cc')
